name: Check Runner Specs

on:
  workflow_dispatch:  # This allows you to trigger manually

jobs:
  check-disk:
    runs-on: runner-extra-capacity  # GitHub-hosted runner
    steps:
      - name: Check free disk space
        run: df -h

      - name: Show available disk space in GB
        run: |
          echo "Available space:"
          df -BG | grep '^/dev/' | awk '{print $4 " available on " $1}'

      - name: Check runner specs
        run: |
          echo "CPU cores: $(nproc)"
          free -h